Repository AY2223S2-CS2103T-T12-4/tp, pull requests merged in 2023-04, with the labels that each got.

#250 Update PPP
  docs/AboutUs.md
  docs/team/chia-yh.md
Labels: type.Task, priority.High

#246 Fix #242
  src/main/java/seedu/socket/model/person/tag/Language.java
  src/test/java/seedu/socket/model/person/tag/LanguageTest.java
Labels: type.FunctionalityBug, priority.High, severity.High

#249 Update DG
  docs/DeveloperGuide.md
Labels: priority.High, severity.Medium, type.DocumentationBug

#248 Update UG, fix documentation bugs
  docs/UserGuide.md
Labels: priority.Normal, severity.Low, type.DocumentationBug

#257 Update PPP
  docs/team/huanghao1998.md
Labels: priority.Low

#258 Update cmang12.md
  docs/team/cmang12.md
Labels: priority.Normal

#255 Fix bug on clear
  docs/UserGuide.md
  docs/images/AssignAfter.png
  docs/images/AssignBefore.png
  docs/images/SortByAddress.png
  docs/images/SortByName.png
  docs/images/SortpjByDeadline.png
  docs/images/SortpjByName.png
  docs/images/Ui.png
  docs/images/UiDescription.png
  docs/images/UnassignAfter.png
  docs/images/UnassignBefore.png
  docs/images/addJohnDoeResult.png
  docs/images/addpjResult.png
  docs/images/edit1Result.png
  docs/images/editpj.png
  docs/images/findAlexDavidResult.png
  docs/images/remove.png
  docs/images/removepj.png
  docs/images/removepj2.png
  src/main/java/seedu/socket/logic/commands/ClearCommand.java
  src/main/java/seedu/socket/model/Socket.java
  src/main/java/seedu/socket/model/project/UniqueProjectList.java
  src/test/java/seedu/socket/logic/commands/ClearCommandTest.java
Labels: type.Enhancement, priority.High

#259 Fix error in AddProjectCommand usage message
  src/main/java/seedu/socket/logic/commands/AddProjectCommand.java
Labels: priority.High

#261 fix error message for editpj
  src/main/java/seedu/socket/logic/commands/EditProjectCommand.java
Labels: priority.High

#260 fix help command error
  docs/UserGuide.md
  src/main/java/seedu/socket/ui/HelpWindow.java
Labels: priority.High

#256 Update DG test case
  docs/DeveloperGuide.md
  docs/images/Ui.png
Labels: type.Enhancement, priority.Normal

#265 Update planned enhancements
  docs/DeveloperGuide.md
  src/main/java/seedu/socket/MainApp.java
Labels: type.Task, priority.High

#264 Update PPP to include contributions to new and existing features
  docs/team/nus-jeff.md
Labels: priority.Low

#263 Update UG & DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#262 standardise phone
  docs/UserGuide.md
  src/main/java/seedu/socket/logic/commands/EditProjectCommand.java
  src/main/java/seedu/socket/logic/commands/RemoveProjectCommand.java
  src/main/java/seedu/socket/ui/HelpWindow.java
Labels: priority.High

#272 Update UG
  docs/UserGuide.md
Labels: priority.High

#270 Update PPP
  docs/team/chia-yh.md
Labels: priority.Normal

#271 edit message in remove
  src/main/java/seedu/socket/logic/commands/RemoveCommand.java
  src/main/java/seedu/socket/logic/commands/RemoveProjectCommand.java
Labels: priority.High

#269 Update planned enhancements
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: priority.High

#273 Fix minor bugs in UG
  docs/UserGuide.md
  docs/images/UiDescription.png
Labels: type.Enhancement, priority.High

#274 Fix grammatical error on the diagram
  docs/images/UiDescription.png
Labels: type.Enhancement, priority.High

#267 Add manual test cases & diagrams in DG, fix errors in UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/PersonPredicateSequenceDiagram.puml
  docs/diagrams/UserInputActivityDiagram.puml
  docs/images/FindSequenceDiagram.png
  docs/images/PersonPredicateSequenceDiagram.png
  docs/images/UserInputActivityDiagram.png
  docs/team/chia-yh.md
  docs/team/cmang12.md
  docs/team/nus-jeff.md
Labels: priority.High

#275 Fix formatting issue
  docs/DeveloperGuide.md
Labels: priority.High

#276 Remove extra line
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#277 update ug for list
  docs/UserGuide.md
  docs/diagrams/ListSequenceDiagram.puml
  docs/images/ListSequenceDiagram.png
Labels: priority.High

#278 Add Use case & update description for find feature in DG
  docs/DeveloperGuide.md
Labels: priority.High

#279 Update PPP
  docs/team/nus-jeff.md
Labels: priority.Normal

#280 Update PPP
  docs/team/huanghao1998.md
Labels: priority.Normal

#281 update ppp
  docs/team/cmang12.md
Labels: priority.Normal

#282 Update output message on ss
  docs/images/remove.png
  docs/images/removepj.png
  docs/images/removepj2.png
Labels: priority.Normal

#284 Update page breaks
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#285 Update page breaks
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#286 Update page breaks
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#287 Update section
  docs/UserGuide.md
Labels: priority.High

#288 Update Diagrams in DG & reason for omitting diagram
  docs/DeveloperGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/PersonPredicateSequenceDiagram.puml
  docs/diagrams/UserInputActivityDiagram.puml
  docs/images/FindSequenceDiagram.png
  docs/images/PersonPredicateSequenceDiagram.png
  docs/images/UserInputActivityDiagram.png
Labels: priority.High

#290 add use cases
  docs/DeveloperGuide.md
  docs/team/cmang12.md
Labels: priority.High

#292 Format documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#294 Update format
  docs/DeveloperGuide.md
Labels: priority.High

#295 Update page breaks
  docs/UserGuide.md
Labels: priority.High

#297 Update PPP
  docs/team/chia-yh.md
Labels: priority.Normal
