Repository AY2223S2-CS2103T-T12-4/tp, pull requests merged in 2023-03, with the labels that each got.

#57 Update AboutUs.md
  docs/AboutUs.md
  docs/images/dillongoh.png
Labels: type.Task

#59 Update use cases in DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Task

#58 Update user stories in DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Task

#60 Update about us
  docs/AboutUs.md
  docs/images/carmen-ang.jpg
  docs/images/github-icon.png
Labels: type.Task

#42 Update individual details, photo in AboutUs.md
  docs/AboutUs.md
  docs/_config.yml
  docs/images/chia-yh.png
Labels: type.Task

#44 Update add, edit features in UserGuide.md
  docs/UserGuide.md
Labels: type.Task

#53 Update the target user profile, value proposition, and user stories in DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Task

#43 Update README.md
  README.md
  docs/_sass/minima/_base.scss
Labels: type.Task

#45 Add skeletal Project Portfolio Page (PPP)
  docs/team/chia-yh.md
Labels: type.Task

#55 Update the glossary in DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Task

#56 Update the non-functional requirements in DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Task

#54 Update use cases in DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Task

#62 Update UserGuide.md
  docs/UserGuide.md
Labels: type.Task

#64 Add skeletal ppp
  docs/AboutUs.md
  docs/team/cmang12.md
Labels: type.Task

#68 Update AboutUs.md
  docs/AboutUs.md
  docs/images/cmang12.png
Labels: type.Task

#63 Update find features in UserGuide.md
  docs/UserGuide.md
Labels: type.Task

#66 Update personal info
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/nus-jeff.png
  docs/team/huanghao1998.md
  docs/team/nus-jeff.md
Labels: type.Task

#67 Update use cases in DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Task

#61 Update Docs - use cases
  docs/DeveloperGuide.md
Labels: type.Task

#70 Update Developer Guide with UC05, UC11 and UC14
  docs/DeveloperGuide.md
Labels: type.Task

#74 Add GitHubProfile class to model.person package
  src/main/java/seedu/address/model/person/GitHubProfile.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/person/GitHubProfileTest.java
Labels: type.Task

#75 Add Language class to model.tag
  src/main/java/seedu/address/model/tag/Language.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/tag/LanguageTest.java
Labels: type.Task

#76 Update Person class to utilise new classes
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/GitHubProfile.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedLanguage.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/GitHubProfileTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/tag/LanguageTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task

#78 Add sort feature
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task

#83 Update HelpWindow.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Task, priority.High

#88 Add command remove
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemoveCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/RemoveCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/GitHubProfile.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/RemoveCommandTest.java
  src/test/java/seedu/address/logic/commands/RemovePersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/RemoveCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/RemovePersonDescriptorBuilder.java
Labels: type.Task, priority.High

#94 Update UserGuide.md for find command
  docs/UserGuide.md
Labels: type.Task, priority.Normal

#91 Update UG on remove command
  docs/UserGuide.md
Labels: type.Task, priority.Normal

#85 Update sort feature
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#89 Update list command
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/model/tag/LanguageContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/tag/TagContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
Labels: type.Task, priority.High

#100 Modify find command & usage message of add command
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/predicate/AddressContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicate/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicate/LanguageContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicate/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicate/PersonContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicate/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicate/ProfileContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicate/TagContainsKeywordsPredicate.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/predicate/AddressContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/LanguageContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/PersonContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/PhoneContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/ProfileContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/TagContainsKeywordsPredicateTest.java
Labels: type.Task, priority.High

#104 Update UserGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.Low

#102 Update list in UserGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.Normal

#103 Update HelpWindow with clickable Hyperlink
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Enhancement, type.Task, priority.Normal

#99 Add undo/redo commands
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/RemoveCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedSocket.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Task, priority.High

#106 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Task, priority.Low

#109 Update UserGuide.md and DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.Low

#112 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Task, priority.Low

#111 Update UG/DG on remove and view feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Enhancement, priority.Low

#114 Fix bug on UX
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: type.Bug, priority.High

#117 Further Improvement on UI
  src/main/java/seedu/socket/ui/PersonListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonDetailCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Enhancement, priority.Low

#120 Fix incorrect path in .gradle
  build.gradle
Labels: type.Bug, severity.Medium

#121 Enable assertions in build.gradle
  build.gradle
Labels: type.Task

#122 Refactor predicate names and file path
  src/main/java/seedu/socket/logic/commands/EditCommand.java
  src/main/java/seedu/socket/logic/commands/FindCommand.java
  src/main/java/seedu/socket/logic/commands/ListCommand.java
  src/main/java/seedu/socket/logic/commands/RemoveCommand.java
  src/main/java/seedu/socket/logic/parser/AddCommandParser.java
  src/main/java/seedu/socket/logic/parser/EditCommandParser.java
  src/main/java/seedu/socket/logic/parser/FindCommandParser.java
  src/main/java/seedu/socket/logic/parser/ListCommandParser.java
  src/main/java/seedu/socket/logic/parser/ParserUtil.java
  src/main/java/seedu/socket/logic/parser/RemoveCommandParser.java
  src/main/java/seedu/socket/model/person/Person.java
  src/main/java/seedu/socket/model/person/predicate/FindCommandAddressPredicate.java
  src/main/java/seedu/socket/model/person/predicate/FindCommandEmailPredicate.java
  src/main/java/seedu/socket/model/person/predicate/FindCommandLanguagePredicate.java
  src/main/java/seedu/socket/model/person/predicate/FindCommandNamePredicate.java
  src/main/java/seedu/socket/model/person/predicate/FindCommandPersonPredicate.java
  src/main/java/seedu/socket/model/person/predicate/FindCommandPhonePredicate.java
  src/main/java/seedu/socket/model/person/predicate/FindCommandProfilePredicate.java
  src/main/java/seedu/socket/model/person/predicate/FindCommandTagPredicate.java
  src/main/java/seedu/socket/model/person/predicate/ListCommandLanguagePredicate.java
  src/main/java/seedu/socket/model/person/predicate/ListCommandTagPredicate.java
  src/main/java/seedu/socket/model/person/predicate/PersonContainsKeywordsPredicate.java
  src/main/java/seedu/socket/model/person/tag/Language.java
  src/main/java/seedu/socket/model/person/tag/Tag.java
  src/main/java/seedu/socket/model/util/SampleDataUtil.java
  src/main/java/seedu/socket/storage/JsonAdaptedLanguage.java
  src/main/java/seedu/socket/storage/JsonAdaptedPerson.java
  src/main/java/seedu/socket/storage/JsonAdaptedTag.java
  src/test/java/seedu/socket/logic/commands/CommandTestUtil.java
  src/test/java/seedu/socket/logic/commands/FindCommandTest.java
  src/test/java/seedu/socket/logic/commands/ListCommandTest.java
  src/test/java/seedu/socket/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/socket/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/socket/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/socket/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/socket/logic/parser/ParserUtilTest.java
  src/test/java/seedu/socket/logic/parser/RemoveCommandParserTest.java
  src/test/java/seedu/socket/logic/parser/SocketParserTest.java
  src/test/java/seedu/socket/model/ModelManagerTest.java
  src/test/java/seedu/socket/model/person/predicate/AddressContainsKeywordsPredicateTest.java
  src/test/java/seedu/socket/model/person/predicate/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/socket/model/person/predicate/LanguageContainsKeywordsPredicateTest.java
  src/test/java/seedu/socket/model/person/predicate/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/socket/model/person/predicate/PersonContainsKeywordsPredicateTest.java
  src/test/java/seedu/socket/model/person/predicate/PhoneContainsKeywordsPredicateTest.java
  src/test/java/seedu/socket/model/person/predicate/ProfileContainsKeywordsPredicateTest.java
  src/test/java/seedu/socket/model/person/predicate/TagContainsKeywordsPredicateTest.java
  src/test/java/seedu/socket/model/tag/LanguageTest.java
  src/test/java/seedu/socket/model/tag/TagTest.java
  src/test/java/seedu/socket/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/socket/testutil/PersonBuilder.java
  src/test/java/seedu/socket/testutil/PersonUtil.java
  src/test/java/seedu/socket/testutil/RemovePersonDescriptorBuilder.java
Labels: priority.Normal

#130 Implement remaining functionality for Project framework
  src/main/java/seedu/socket/model/ReadOnlySocket.java
  src/main/java/seedu/socket/model/Socket.java
  src/main/java/seedu/socket/model/person/Person.java
  src/main/java/seedu/socket/model/person/UniquePersonList.java
  src/main/java/seedu/socket/model/project/ProjectDeadline.java
  src/main/java/seedu/socket/model/project/ProjectRepoHost.java
  src/main/java/seedu/socket/model/project/ProjectRepoName.java
  src/main/java/seedu/socket/model/util/SampleDataUtil.java
  src/main/java/seedu/socket/storage/JsonAdaptedPerson.java
  src/main/java/seedu/socket/storage/JsonAdaptedProject.java
  src/main/java/seedu/socket/storage/JsonSerializableSocket.java
  src/main/java/seedu/socket/storage/JsonSocketStorage.java
  src/test/data/JsonSerializableSocketTest/duplicatePersonSocket.json
  src/test/data/JsonSerializableSocketTest/duplicateProjectSocket.json
  src/test/data/JsonSerializableSocketTest/invalidPersonSocket.json
  src/test/data/JsonSerializableSocketTest/invalidProjectSocket.json
  src/test/data/JsonSerializableSocketTest/missingProjectMemberInPersonsSocket.json
  src/test/data/JsonSerializableSocketTest/typicalPersonsSocket.json
  src/test/data/JsonSerializableSocketTest/typicalProjectsSocket.json
  src/test/java/seedu/socket/model/SocketTest.java
  src/test/java/seedu/socket/model/project/ProjectRepoHostTest.java
  src/test/java/seedu/socket/model/project/ProjectRepoNameTest.java
  src/test/java/seedu/socket/storage/JsonAdaptedProjectTest.java
  src/test/java/seedu/socket/storage/JsonSerializableSocketTest.java
  src/test/java/seedu/socket/testutil/TypicalPersons.java
  src/test/java/seedu/socket/testutil/TypicalProjects.java
Labels: priority.Normal

#147 Update VALIDATION_REGEX in Tag
  src/main/java/seedu/socket/model/person/tag/Tag.java
  src/test/java/seedu/socket/model/tag/TagTest.java
Labels: priority.High

#128 Update UI
  docs/images/Ui.png
  src/main/java/seedu/socket/logic/LogicManager.java
  src/main/java/seedu/socket/ui/HelpWindow.java
  src/main/java/seedu/socket/ui/PersonListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
Labels: type.Enhancement

#149 Add meeting to project
  src/main/java/seedu/socket/model/Socket.java
  src/main/java/seedu/socket/model/project/Project.java
  src/main/java/seedu/socket/model/project/ProjectMeeting.java
  src/main/java/seedu/socket/model/project/UniqueProjectList.java
  src/main/java/seedu/socket/model/util/SampleDataUtil.java
  src/main/java/seedu/socket/storage/JsonAdaptedProject.java
  src/main/java/seedu/socket/storage/JsonSerializableSocket.java
  src/test/data/JsonSerializableSocketTest/duplicateProjectSocket.json
  src/test/data/JsonSerializableSocketTest/invalidProjectSocket.json
  src/test/data/JsonSerializableSocketTest/missingProjectMemberInPersonsSocket.json
  src/test/data/JsonSerializableSocketTest/typicalProjectsSocket.json
  src/test/java/seedu/socket/logic/commands/CommandTestUtil.java
  src/test/java/seedu/socket/model/project/ProjectMeetingTest.java
  src/test/java/seedu/socket/model/project/ProjectTest.java
  src/test/java/seedu/socket/storage/JsonAdaptedProjectTest.java
  src/test/java/seedu/socket/testutil/ProjectBuilder.java
  src/test/java/seedu/socket/testutil/TypicalProjects.java
Labels: priority.High

#150 Add deletepj command for removing Project
  src/main/java/seedu/socket/commons/core/Messages.java
  src/main/java/seedu/socket/logic/commands/DeleteProjectCommand.java
  src/main/java/seedu/socket/logic/parser/DeleteProjectCommandParser.java
  src/main/java/seedu/socket/logic/parser/SocketParser.java
  src/main/java/seedu/socket/model/Model.java
  src/main/java/seedu/socket/model/ModelManager.java
  src/main/java/seedu/socket/model/person/predicate/FindCommandProjectNamePredicate.java
  src/test/java/seedu/socket/logic/commands/AddCommandTest.java
  src/test/java/seedu/socket/logic/commands/CommandTestUtil.java
  src/test/java/seedu/socket/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/socket/logic/commands/DeleteProjectCommandTest.java
  src/test/java/seedu/socket/logic/parser/DeleteProjectCommandParserTest.java
  src/test/java/seedu/socket/logic/parser/SocketParserTest.java
  src/test/java/seedu/socket/model/ModelManagerTest.java
  src/test/java/seedu/socket/testutil/SocketBuilder.java
  src/test/java/seedu/socket/testutil/TypicalIndexes.java
Labels: priority.High

#153 Fix lack of updates to `Person` references
  src/main/java/seedu/socket/model/Socket.java
  src/main/java/seedu/socket/model/project/Project.java
  src/main/java/seedu/socket/model/project/UniqueProjectList.java
  src/test/java/seedu/socket/logic/commands/EditCommandTest.java
  src/test/java/seedu/socket/logic/commands/RemoveCommandTest.java
Labels: type.Bug, severity.High

#154 Add command clearpj
  src/main/java/seedu/socket/logic/commands/ClearCommand.java
  src/main/java/seedu/socket/logic/commands/ClearProjectCommand.java
  src/main/java/seedu/socket/logic/parser/SocketParser.java
  src/main/java/seedu/socket/model/Model.java
  src/main/java/seedu/socket/model/ModelManager.java
  src/test/java/seedu/socket/logic/commands/AddCommandTest.java
  src/test/java/seedu/socket/logic/commands/ClearProjectCommandTest.java
  src/test/java/seedu/socket/logic/parser/SocketParserTest.java
Labels: priority.High

#157 Add EditProjectCommand.java
  src/main/java/seedu/socket/logic/commands/EditProjectCommand.java
  src/main/java/seedu/socket/logic/parser/CliSyntax.java
  src/main/java/seedu/socket/logic/parser/EditProjectCommandParser.java
  src/main/java/seedu/socket/logic/parser/ParserUtil.java
  src/main/java/seedu/socket/logic/parser/SocketParser.java
  src/test/java/seedu/socket/logic/commands/CommandTestUtil.java
  src/test/java/seedu/socket/logic/commands/EditProjectCommandTest.java
  src/test/java/seedu/socket/logic/commands/EditProjectDescriptorTest.java
  src/test/java/seedu/socket/logic/parser/EditProjectCommandParserTest.java
  src/test/java/seedu/socket/logic/parser/SocketParserTest.java
  src/test/java/seedu/socket/testutil/EditProjectDescriptorBuilder.java
  src/test/java/seedu/socket/testutil/ProjectBuilder.java
Labels: type.Task, priority.High

#156 Add command clearpj
  src/main/java/seedu/socket/logic/commands/ClearProjectCommand.java
Labels: type.Enhancement

#160 Update DG with implementation of sort feature
  docs/DeveloperGuide.md
Labels: priority.Normal

#155 Update find command format in HelpWindow.java
  src/main/java/seedu/socket/ui/HelpWindow.java
Labels: priority.Low

#161 Update UG with `deletepj` command information
  docs/UserGuide.md
Labels: type.Task

#162 Update UI
  src/main/java/seedu/socket/logic/Logic.java
  src/main/java/seedu/socket/logic/LogicManager.java
  src/main/java/seedu/socket/ui/MainWindow.java
  src/main/java/seedu/socket/ui/PersonDetailPanel.java
  src/main/java/seedu/socket/ui/ProjectCard.java
  src/main/java/seedu/socket/ui/ProjectListPanel.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ProjectListCard.fxml
  src/main/resources/view/ProjectListPanel.fxml
Labels: type.Enhancement

#166 Update Developer Guide for Find Command implementation
  docs/DeveloperGuide.md
Labels: priority.Normal

#167 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: priority.High

#168 Add removepj
  src/main/java/seedu/socket/logic/commands/EditProjectCommand.java
  src/main/java/seedu/socket/logic/commands/RemoveProjectCommand.java
  src/main/java/seedu/socket/logic/parser/ParserUtil.java
  src/main/java/seedu/socket/logic/parser/RemoveProjectCommandParser.java
  src/main/java/seedu/socket/logic/parser/SocketParser.java
  src/main/java/seedu/socket/model/project/ProjectDeadline.java
  src/main/java/seedu/socket/model/project/ProjectMeeting.java
  src/test/java/seedu/socket/logic/commands/EditProjectCommandTest.java
  src/test/java/seedu/socket/logic/commands/RemoveProjectCommandTest.java
  src/test/java/seedu/socket/logic/commands/RemoveProjectDescriptorTest.java
  src/test/java/seedu/socket/logic/parser/RemoveProjectCommandParserTest.java
  src/test/java/seedu/socket/logic/parser/SocketParserTest.java
  src/test/java/seedu/socket/testutil/ProjectBuilder.java
  src/test/java/seedu/socket/testutil/RemoveProjectDescriptorBuilder.java
Labels: priority.High

#169 Add unassign command
  docs/UserGuide.md
  src/main/java/seedu/socket/logic/commands/UnassignCommand.java
  src/main/java/seedu/socket/logic/parser/SocketParser.java
  src/main/java/seedu/socket/logic/parser/UnassignCommandParser.java
  src/main/java/seedu/socket/model/project/Project.java
  src/test/java/seedu/socket/logic/commands/UnassignCommandTest.java
  src/test/java/seedu/socket/logic/parser/SocketParserTest.java
  src/test/java/seedu/socket/logic/parser/UnassignCommandParserTest.java
  src/test/java/seedu/socket/model/project/ProjectTest.java
Labels: priority.High

#172 Restriction on number of tags
  src/main/java/seedu/socket/logic/commands/AddCommand.java
  src/main/java/seedu/socket/logic/commands/EditCommand.java
  src/test/java/seedu/socket/logic/commands/AddCommandTest.java
  src/test/java/seedu/socket/logic/commands/EditCommandTest.java
Labels: type.Enhancement

#165 Add command addpj
  src/main/java/seedu/socket/logic/commands/AddProjectCommand.java
  src/main/java/seedu/socket/logic/commands/EditProjectCommand.java
  src/main/java/seedu/socket/logic/parser/AddProjectCommandParser.java
  src/main/java/seedu/socket/logic/parser/ParserUtil.java
  src/main/java/seedu/socket/logic/parser/SocketParser.java
  src/test/java/seedu/socket/logic/commands/AddProjectCommandTest.java
  src/test/java/seedu/socket/logic/commands/RemoveProjectCommandTest.java
  src/test/java/seedu/socket/logic/parser/AddProjectCommandParserTest.java
  src/test/java/seedu/socket/logic/parser/SocketParserTest.java
  src/test/java/seedu/socket/testutil/ProjectBuilder.java
  src/test/java/seedu/socket/testutil/ProjectUtil.java
Labels: priority.High

#171 Update use cases for sortpj and unassign commands
  docs/DeveloperGuide.md
Labels: priority.Normal

#175 Add ability to assign persons to projects in SOCket
  src/main/java/seedu/socket/logic/commands/AssignCommand.java
  src/main/java/seedu/socket/logic/parser/AssignCommandParser.java
  src/main/java/seedu/socket/logic/parser/SocketParser.java
  src/test/java/seedu/socket/logic/commands/AssignCommandTest.java
  src/test/java/seedu/socket/logic/parser/AssignCommandParserTest.java
  src/test/java/seedu/socket/logic/parser/SocketParserTest.java
Labels: priority.High

#177 Update UG with images for add, edit, reshuffle sections under features
  docs/UserGuide.md
  docs/images/addJohnDoeResult.png
  docs/images/edit1Result.png
Labels: type.Task

#180 Refine duplicate checking for Project instances
  src/main/java/seedu/socket/model/project/ProjectName.java
  src/test/java/seedu/socket/model/person/NameTest.java
  src/test/java/seedu/socket/model/project/ProjectNameTest.java
  src/test/java/seedu/socket/model/project/ProjectTest.java
Labels: type.Enhancement, priority.High

#184 Update DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/diagrams/UpdateProjectOnDeletePersonSequenceDiagram.puml
  docs/images/UpdateProjectOnDeletePersonSequenceDiagram.png
Labels: type.Task

#179 Update on DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/AssignAfter.png
  docs/images/AssignBefore.png
  docs/images/SortByAddress.png
  docs/images/SortByName.png
  docs/images/SortpjByDeadline.png
  docs/images/SortpjByName.png
  docs/images/Ui.png
  docs/images/UiDescription.png
  docs/images/UnassignAfter.png
  docs/images/UnassignBefore.png
  docs/images/addJohnDoeResult.png
  docs/images/addpjResult.png
  docs/images/assignResult.png
  docs/images/edit1Result.png
  docs/images/editpj.png
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
  docs/images/remove.png
  docs/images/removepj.png
  docs/images/removepj1.png
  docs/images/removepj2.png
  docs/team/huanghao1998.md
  src/main/java/seedu/socket/commons/core/GuiSettings.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement, priority.High

#187 Fix ToC
  docs/UserGuide.md
Labels: type.Task

#188 Fix ToC
  docs/UserGuide.md
Labels: type.Task

#191 Update DG
  docs/DeveloperGuide.md
Labels: type.Enhancement, type.Task, priority.Normal

#190 Update Ui and image
  docs/DeveloperGuide.md
  docs/images/UiClassDiagram.png
  docs/images/helpMessage.png
  src/main/java/seedu/socket/ui/HelpWindow.java
  src/main/java/seedu/socket/ui/ProjectCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/ProjectListCard.fxml
Labels: type.Enhancement, priority.Normal

#195 Update UG
  docs/UserGuide.md
Labels: type.Enhancement, type.Task, priority.Normal

#197 Modify page breaks
  docs/UserGuide.md
Labels: type.Task

#196 Modify string outputs
  src/main/java/seedu/socket/logic/commands/AddCommand.java
  src/main/java/seedu/socket/logic/commands/ClearCommand.java
  src/main/java/seedu/socket/logic/commands/ClearProjectCommand.java
  src/main/java/seedu/socket/logic/commands/EditCommand.java
  src/main/java/seedu/socket/logic/commands/SortCommand.java
  src/main/java/seedu/socket/logic/commands/SortProjectCommand.java
  src/main/java/seedu/socket/model/person/Person.java
  src/main/java/seedu/socket/model/project/Project.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonDetailCard.fxml
  src/main/resources/view/PersonDetailPanel.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/ProjectListCard.fxml
  src/main/resources/view/ProjectListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StatusBarFooter.fxml
Labels: type.Enhancement, type.Task

#198 Refactor test case names and location
  src/test/java/seedu/socket/model/person/predicate/FindCommandAddressPredicateTest.java
  src/test/java/seedu/socket/model/person/predicate/FindCommandEmailPredicateTest.java
  src/test/java/seedu/socket/model/person/predicate/FindCommandLanguagePredicateTest.java
  src/test/java/seedu/socket/model/person/predicate/FindCommandNamePredicateTest.java
  src/test/java/seedu/socket/model/person/predicate/FindCommandPersonPredicateTest.java
  src/test/java/seedu/socket/model/person/predicate/FindCommandPhonePredicateTest.java
  src/test/java/seedu/socket/model/person/predicate/FindCommandProfilePredicateTest.java
  src/test/java/seedu/socket/model/person/predicate/FindCommandTagPredicateTest.java
  src/test/java/seedu/socket/model/person/tag/LanguageTest.java
  src/test/java/seedu/socket/model/person/tag/TagTest.java
Labels: priority.Low

#199 Add test cases for project fields in ParserUtilTest.java
  src/test/java/seedu/socket/logic/parser/ParserUtilTest.java
Labels: priority.Low

#202 Fix bug and update ss
  docs/UserGuide.md
  docs/images/AssignAfter.png
  docs/images/AssignBefore.png
  docs/images/SortByAddress.png
  docs/images/SortByName.png
  docs/images/SortpjByDeadline.png
  docs/images/SortpjByName.png
  docs/images/UiDescription.png
  docs/images/UnassignAfter.png
  docs/images/UnassignBefore.png
  docs/images/addJohnDoeResult.png
  docs/images/addpjResult.png
  docs/images/edit1Result.png
  docs/images/editpj.png
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
  docs/images/remove.png
  docs/images/removepj.png
  docs/images/removepj2.png
  src/main/java/seedu/socket/logic/commands/AssignCommand.java
  src/main/java/seedu/socket/logic/commands/UnassignCommand.java
Labels: type.Enhancement, type.Bug

#204 Reformat UG/DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Enhancement, type.Task

#205 Reformat UG/DG breaks
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Enhancement, type.Task

#206 Reshuffle page breaks
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Enhancement, type.Task

#207 Reshuffle page breaks
  docs/DeveloperGuide.md
Labels: type.Enhancement, type.Task

#208 Reshuffle page breaks
  docs/DeveloperGuide.md
Labels: type.Enhancement, type.Task

#209 Add page break
  docs/DeveloperGuide.md
Labels: type.Enhancement, type.Task
